"""Initial schema with legal_cases and url_tracker tables

Revision ID: 60f6a33a457f
Revises: 
Create Date: 2025-10-21 05:42:00.564945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f6a33a457f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legal_cases', sa.Column('court_type', sa.Enum('SUPREME', 'HIGH', 'TRIBUNAL', 'DISTRICT', 'APPELLATE', 'SESSIONS', 'MAGISTRATE', name='courttype'), nullable=True))
    op.add_column('legal_cases', sa.Column('court_name', sa.String(length=200), nullable=True))
    op.add_column('legal_cases', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('legal_cases', sa.Column('document_type', sa.String(length=100), nullable=True))
    op.add_column('legal_cases', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('legal_cases', sa.Column('scrape_tier', sa.Integer(), nullable=True))
    op.add_column('legal_cases', sa.Column('pagination_page', sa.Integer(), nullable=True))
    op.add_column('legal_cases', sa.Column('is_historical', sa.Boolean(), nullable=True))
    op.create_index('idx_court_year', 'legal_cases', ['court_type', 'year'], unique=False)
    op.create_index('idx_document_year', 'legal_cases', ['document_type', 'year'], unique=False)
    op.create_index('idx_tier_downloaded', 'legal_cases', ['scrape_tier', 'pdf_downloaded'], unique=False)
    op.create_index(op.f('ix_legal_cases_court_name'), 'legal_cases', ['court_name'], unique=False)
    op.create_index(op.f('ix_legal_cases_court_type'), 'legal_cases', ['court_type'], unique=False)
    op.create_index(op.f('ix_legal_cases_document_type'), 'legal_cases', ['document_type'], unique=False)
    op.create_index(op.f('ix_legal_cases_year'), 'legal_cases', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_cases_year'), table_name='legal_cases')
    op.drop_index(op.f('ix_legal_cases_document_type'), table_name='legal_cases')
    op.drop_index(op.f('ix_legal_cases_court_type'), table_name='legal_cases')
    op.drop_index(op.f('ix_legal_cases_court_name'), table_name='legal_cases')
    op.drop_index('idx_tier_downloaded', table_name='legal_cases')
    op.drop_index('idx_document_year', table_name='legal_cases')
    op.drop_index('idx_court_year', table_name='legal_cases')
    op.drop_column('legal_cases', 'is_historical')
    op.drop_column('legal_cases', 'pagination_page')
    op.drop_column('legal_cases', 'scrape_tier')
    op.drop_column('legal_cases', 'year')
    op.drop_column('legal_cases', 'document_type')
    op.drop_column('legal_cases', 'state')
    op.drop_column('legal_cases', 'court_name')
    op.drop_column('legal_cases', 'court_type')
    # ### end Alembic commands ###
